#!/usr/bin/env python3
"""validate_generated_skill.py

Zero-dependency validator for Claude Agent Skill packages generated by context7-skill-wizard.

Usage:  python3 scripts/validate_generated_skill.py <skill-dir>
Exit:   0 = all checks pass (ready to package)
        1 = one or more checks failed (fix before packaging)
        2 = structural error (missing SKILL.md, bad args)
"""

import sys
import os
import re

PASS = "✅ PASS"
FAIL = "❌ FAIL"


def check(label, condition, fix=""):
    status = PASS if condition else FAIL
    print(f"  {status}  {label}")
    if not condition and fix:
        print(f"           → {fix}")
    return condition


def parse_frontmatter(content):
    """Return (frontmatter_dict, body_text) from SKILL.md content."""
    lines = content.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, content

    fm_lines = []
    body_start = len(lines)
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            body_start = i + 1
            break
        fm_lines.append(lines[i])

    fm = {}
    for line in fm_lines:
        if ":" in line:
            key, _, val = line.partition(":")
            fm[key.strip()] = val.strip()

    body = "\n".join(lines[body_start:])
    return fm, body


def count_non_empty_lines(text):
    return sum(1 for line in text.splitlines() if line.strip())


def main():
    if len(sys.argv) < 2:
        print("Usage: validate_generated_skill.py <skill-dir>")
        sys.exit(2)

    skill_dir = sys.argv[1].rstrip("/\\")

    if not os.path.isdir(skill_dir):
        print(f"ERROR: Directory not found: {skill_dir}")
        sys.exit(2)

    skill_md_path = os.path.join(skill_dir, "SKILL.md")
    if not os.path.isfile(skill_md_path):
        print(f"ERROR: SKILL.md not found in {skill_dir}")
        sys.exit(2)

    with open(skill_md_path, "r", encoding="utf-8") as f:
        content = f.read()

    fm, body = parse_frontmatter(content)
    name = fm.get("name", "")
    desc = fm.get("description", "")
    folder_name = os.path.basename(os.path.abspath(skill_dir))
    body_line_count = count_non_empty_lines(body)

    results = []

    # ── NAME ────────────────────────────────────────────────────────────────
    print(f"\n{'═'*58}")
    print(f"  SKILL VALIDATION  ›  {folder_name}")
    print(f"{'═'*58}")

    print("\n▸ NAME")
    results.append(check(
        "name field present",
        bool(name),
        "Add 'name: your-skill-name' to YAML frontmatter"
    ))
    results.append(check(
        "name charset: lowercase letters, numbers, hyphens only",
        bool(name) and bool(re.match(r'^[a-z0-9]+(-[a-z0-9]+)*$', name)),
        "Replace underscores/spaces/capitals with hyphens"
    ))
    results.append(check(
        f"name length ≤ 64 chars  (actual: {len(name)})",
        len(name) <= 64,
        "Shorten the name field"
    ))
    results.append(check(
        "no reserved words in name ('anthropic', 'claude')",
        "anthropic" not in name and name != "claude",
        "Remove reserved platform identifiers"
    ))
    results.append(check(
        "folder name matches skill name field",
        folder_name == name,
        f"Rename folder from '{folder_name}' to '{name}'"
    ))

    # ── DESCRIPTION ─────────────────────────────────────────────────────────
    print("\n▸ DESCRIPTION")
    desc_len = len(desc)
    results.append(check(
        "description field present",
        bool(desc),
        "Add 'description: ...' to YAML frontmatter"
    ))
    results.append(check(
        f"description ≤ 1024 chars  (actual: {desc_len})",
        desc_len <= 1024,
        "Trim description to fit 1024-char hard cap"
    ))
    results.append(check(
        f"description ≥ 100 chars  (actual: {desc_len})",
        desc_len >= 100,
        "Add trigger phrases and usage context — description is too sparse"
    ))
    results.append(check(
        "no first-person phrasing ('I can', 'I will', 'I help')",
        not re.search(r'\bi (can|will|help|provide)\b', desc, re.I),
        "Rewrite in third person: 'Provides...' not 'I can provide...'"
    ))
    results.append(check(
        "no second-person phrasing ('You can', 'You will')",
        not re.search(r'\byou (can|will|should)\b', desc, re.I),
        "Rewrite in third person"
    ))
    results.append(check(
        "no XML tags in description",
        "<" not in desc and ">" not in desc,
        "Strip all XML/HTML tags from description field"
    ))
    results.append(check(
        "no 'anthropic' in description",
        "anthropic" not in desc.lower(),
        "Remove reserved platform word 'anthropic'"
    ))

    # ── BODY ────────────────────────────────────────────────────────────────
    print("\n▸ BODY")
    results.append(check(
        f"body ≤ 500 non-empty lines  (actual: {body_line_count})",
        body_line_count <= 500,
        "Move verbose content (large code blocks, full API tables) to references/"
    ))
    results.append(check(
        "no deeply nested reference paths (references/a/b.md)",
        not re.search(r'references/[^\s/]+/[^\s/]+\.(md|txt)', body),
        "Flatten to one level: references/file.md not references/subdir/file.md"
    ))
    results.append(check(
        "no hardcoded secrets or API keys",
        not re.search(
            r'(sk-[A-Za-z0-9]{20,}|api[_-]?key\s*[:=]\s*["\'][^"\']{8,}|bearer\s+[A-Za-z0-9]{20,})',
            body, re.I
        ),
        "Remove all hardcoded credentials — use environment variables"
    ))
    results.append(check(
        "no README.md in skill directory",
        not os.path.isfile(os.path.join(skill_dir, "README.md")),
        "Delete README.md — all documentation belongs in SKILL.md"
    ))

    # ── STRUCTURE ───────────────────────────────────────────────────────────
    print("\n▸ STRUCTURE")
    results.append(check(
        "folder name uses kebab-case",
        bool(re.match(r'^[a-z0-9]+(-[a-z0-9]+)*$', folder_name)),
        "Rename folder to lowercase-kebab-case"
    ))

    refs_dir = os.path.join(skill_dir, "references")
    has_nested_refs = False
    if os.path.isdir(refs_dir):
        for entry in os.scandir(refs_dir):
            if entry.is_dir():
                has_nested_refs = True
                break
    results.append(check(
        "references/ has no subdirectories (one level deep)",
        not has_nested_refs,
        "Remove subdirectories inside references/ — all .md files must be at references/*.md"
    ))

    scripts_dir = os.path.join(skill_dir, "scripts")
    if os.path.isdir(scripts_dir):
        scripts = [f for f in os.listdir(scripts_dir) if f.endswith(".py")]
        if scripts:
            results.append(check(
                "Python scripts present (found in scripts/)",
                True
            ))

    # ── SUMMARY ─────────────────────────────────────────────────────────────
    passed = sum(1 for r in results if r)
    total = len(results)
    failed = total - passed

    print(f"\n{'═'*58}")
    if failed == 0:
        print(f"  ✅  ALL {total} CHECKS PASSED  —  ready to package as ZIP")
    else:
        print(f"  ❌  {failed} of {total} checks failed  —  fix before packaging")
    print(f"{'═'*58}\n")

    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
