#!/usr/bin/env bash
# Phase 2: Writes session-state.md to the durable knowledge directory.
# Reads trajectory manifest from /tmp/trajectory_manifest.json.
# Usage: ./synthesize_state.sh --knowledge-dir /path --session-id compact_123

set -euo pipefail

KNOWLEDGE_DIR=".gemini/antigravity/knowledge"
SESSION_ID="compact_$(date +%s)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --knowledge-dir) KNOWLEDGE_DIR="$2"; shift 2 ;;
    --session-id) SESSION_ID="$2"; shift 2 ;;
    *) shift ;;
  esac
done

mkdir -p "$KNOWLEDGE_DIR"
STATE_FILE="${KNOWLEDGE_DIR}/session-state.md"

# Agent populates these values from session analysis before invoking this script.
# The agent must write /tmp/session_state_payload.json with the required fields first.
PAYLOAD_FILE="/tmp/session_state_payload.json"

if [[ -f "$PAYLOAD_FILE" ]]; then
  OBJECTIVE=$(jq -r '.current_objective // "Not specified"' "$PAYLOAD_FILE")
  DECISIONS=$(jq -r '.finalized_decisions // "None recorded"' "$PAYLOAD_FILE")
  MODIFIED=$(jq -r '.modified_files // "None"' "$PAYLOAD_FILE")
  BLOCKERS=$(jq -r '.active_blockers // "None"' "$PAYLOAD_FILE")
  NEXT_ACTION=$(jq -r '.next_action_delta // "Resume from last known state"' "$PAYLOAD_FILE")
else
  OBJECTIVE="[Agent must populate from session analysis]"
  DECISIONS="[Agent must populate from session analysis]"
  MODIFIED="[Agent must populate from session analysis]"
  BLOCKERS="[Agent must populate from session analysis]"
  NEXT_ACTION="[Agent must populate from session analysis]"
fi

cat > "$STATE_FILE" <<EOF
# Session State — ${SESSION_ID}
_Generated by context-compact skill. Written in 3rd-person executive director persona._

## Current Objective
${OBJECTIVE}

## Finalized Decisions
${DECISIONS}

## Modified Files
${MODIFIED}

## Active Blockers
${BLOCKERS}

## Next Action Delta
${NEXT_ACTION}

---
_Compacted at: $(date -u +"%Y-%m-%dT%H:%M:%SZ") | Session ID: ${SESSION_ID}_
EOF

echo "{\"status\": \"OK\", \"path\": \"${STATE_FILE}\", \"session_id\": \"${SESSION_ID}\"}"
